return {
  icons = {
    mappings = vim.g.have_nerd_font,
    keys = vim.g.have_nerd_font and {} or {
      Up = '<Up> ',
      Down = '<Down> ',
      Left = '<Left> ',
      Right = '<Right> ',
      C = '<C-…> ',
      M = '<M-…> ',
      D = '<D-…> ',
      S = '<S-…> ',
      CR = '<CR> ',
      Esc = '<Esc> ',
      ScrollWheelDown = '<ScrollWheelDown> ',
      ScrollWheelUp = '<ScrollWheelUp> ',
      NL = '<NL> ',
      BS = '<BS> ',
      Space = '<Space> ',
      Tab = '<Tab> ',
      F1 = '<F1>',
      F2 = '<F2>',
      F3 = '<F3>',
      F4 = '<F4>',
      F5 = '<F5>',
      F6 = '<F6>',
      F7 = '<F7>',
      F8 = '<F8>',
      F9 = '<F9>',
      F10 = '<F10>',
      F11 = '<F11>',
      F12 = '<F12>',
    },
  },
  spec = {
    { '<leader>c', group = '[C]ode', mode = { 'n', 'x' } },
    { '<leader>d', group = '[D]ocument' },
    { '<leader>r', group = '[R]ename' },
    { '<leader>f', group = '[F]ind' },
    { '<leader>ft', desc = '[F]ind [T]odos' },
    { '<leader>w', group = '[W]orkspace' },
    { '<leader>s', group = '[S]ave' },
    { '<leader>ss', desc = '[S]ave current buffer' },
    { '<leader>sa', desc = '[S]ave [A]ll buffers' },
    { '<leader>t', group = '[T]oggle' },
    { '<leader>h', group = 'Git [H]unk', mode = { 'n', 'v' } },
    { 'gs', group = 'Surround' },
    { 'gsa', desc = 'Surround [A]dd' },
    { 'gsd', desc = 'Surround [D]elete' },
    { 'gsr', desc = 'Surround [R]eplace' },
    { 'gsf', desc = 'Surround [F]ind right' },
    { 'gsF', desc = 'Surround [F]ind left' },
    { 'gsh', desc = 'Surround [H]ighlight' },
    { 'gsn', desc = 'Surround update [N] lines' },
  },
}
